### ISSUE TITLE
hdf5: filenames could be more meaningful

### ISSUE THREAD

**Issue by kortschak** [gonum/hdf5#28]
I think we can do better than ~single significant letter filenames.

**Comment by sbinet** [comment]
sure. I initially went with this naming convention for users who already had exposure to the C API of HDF5.

**Comment by kortschak** [comment]
Yeah, I figured that while looking through the C. What I was thinking after noticing that was that we could have `h5?_<real_name>.go`, so for example `h5i_identifier.go`
