### ISSUE TITLE
go get gonum.org/v1/hdf5 failed

### ISSUE THREAD

**Issue by Michaeljy** [gonum/hdf5#84]
### What are you trying to do?
go get gonum.org/v1/hdf5

### What did you do?

go get gonum.org/v1/hdf5

### What did you expect to happen?

successed

### What actually happened?

# gonum.org/v1/hdf5
go\pkg\mod\gonum.org\v1\hdf5@v0.0.0-20210714002203-8c5d23bc6946\cgoflags.go:14:11: fatal error: hdf5.h: No such file or directory
   14 | // #include "hdf5.h"
      |           ^~~~~~~~
compilation terminated.

### What version of Go, Gonum, Gonum/netlib and libhdf5 are you using?

go version go1.16.3 windows/amd64
hdf5@v0.0.0-20210714002203-8c5d23bc6946

### Does this issue reproduce with the current master?
yes

**Comment by kortschak** [comment]
Thank you for the report. Just an obvious question: do you have the hdf5 libraries installed? You can see [here](https://github.com/gonum/hdf5/blob/8c5d23bc694680a26a7f03eff4243dc753f0501b/.github/workflows/ci.yml#L49-L56) how they are installed by the CI builder during testing.

**Comment by Michaeljy** [comment]
Thank you
